[package]
name = "sidechain-mc-hash"
version = "0.1.0"
edition = "2021"
description = "Logic for putting a main chain block reference in digest and inherent data"

[dependencies]
async-trait = { workspace = true }
sp-consensus-slots = { workspace = true, features = ["std"] }
sidechain-domain = { workspace = true, features = ["std"] }
sp-consensus = { workspace = true }
sp-blockchain = { workspace = true }
sp-inherents = { workspace = true, features = ["std"] }
sp-runtime = { workspace = true, features = ["std"] }
sp-timestamp = { workspace = true }
thiserror = { workspace = true }
derive-new = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
derive-new = { workspace = true }

[features]
mock = ["derive-new"]
